
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiladorpascal;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 49;
  public static final int FUNCTION = 12;
  public static final int MULT = 39;
  public static final int CHAR = 27;
  public static final int CHAR_LITERAL = 50;
  public static final int GE = 36;
  public static final int SLASH = 40;
  public static final int INTEGER = 28;
  public static final int LPAREN = 8;
  public static final int REPEAT = 25;
  public static final int MINUS = 38;
  public static final int FOR = 21;
  public static final int WRITE = 2;
  public static final int RPAREN = 9;
  public static final int NOT = 45;
  public static final int AND = 43;
  public static final int SEMICOLON = 6;
  public static final int LT = 33;
  public static final int RECORD = 17;
  public static final int TYPE = 16;
  public static final int OR = 44;
  public static final int COMMA = 5;
  public static final int DIV = 41;
  public static final int BEGIN = 13;
  public static final int UNTIL = 26;
  public static final int PLUS = 37;
  public static final int ASSIGN = 30;
  public static final int IF = 18;
  public static final int DOT = 4;
  public static final int LE = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 29;
  public static final int TRUE = 47;
  public static final int error = 1;
  public static final int PROGRAM = 10;
  public static final int MOD = 42;
  public static final int NEQ = 32;
  public static final int EQ = 31;
  public static final int COLON = 7;
  public static final int ELSE = 20;
  public static final int READ = 3;
  public static final int TO = 22;
  public static final int WHILE = 24;
  public static final int THEN = 19;
  public static final int END = 14;
  public static final int FALSE = 46;
  public static final int GT = 34;
  public static final int VAR = 15;
  public static final int PROCEDURE = 11;
  public static final int DO = 23;
  public static final int INTEGER_LITERAL = 51;
  public static final int IDENTIFIER = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WRITE",
  "READ",
  "DOT",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "LPAREN",
  "RPAREN",
  "PROGRAM",
  "PROCEDURE",
  "FUNCTION",
  "BEGIN",
  "END",
  "VAR",
  "TYPE",
  "RECORD",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "TO",
  "DO",
  "WHILE",
  "REPEAT",
  "UNTIL",
  "CHAR",
  "INTEGER",
  "BOOLEAN",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "PLUS",
  "MINUS",
  "MULT",
  "SLASH",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "FALSE",
  "TRUE",
  "IDENTIFIER",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "INTEGER_LITERAL"
  };
}

